using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Video;

namespace BattleAtlas
{
    // Plays pre-rendered Soldier View media strictly slaved to the
    // BattleClock (plan section 10.1). The clock is the only source of
    // historical time: entering forces 1x speed (the media is real-time),
    // play/pause drives clock and video together, seeking moves the clock
    // and then settles the decoder, and exiting leaves the clock exactly
    // where it was — Atlas resumes at the same battle second.
    //
    // Media lives under StreamingAssets (gitignored; generated by
    // reconstruction/scripts/generate_dev_proxy.sh in Phase 1). Missing full
    // media falls back to the proxy with a warning; missing proxy refuses
    // entry — there is nothing truthful to show.
    public class SoldierViewPlayer : MonoBehaviour
    {
        public BattleClock clock;

        // Resync when clock/video disagree by more than this many frames
        // while playing freely; after an explicit seek settles we require
        // Gate P1's one-frame agreement (SoldierViewMath.WithinOneFrame).
        public float resyncThresholdFrames = 2f;

        public ViewpointDefinition Active { get; private set; }
        public bool InSoldierView => Active != null;
        public bool SeekInProgress { get; private set; }
        public double CurrentDriftFrames { get; private set; }
        public double LastSeekLatencyMs { get; private set; }
        public readonly List<double> SeekLatenciesMs = new List<double>();
        public string LastWarning { get; private set; }
        public bool UsingProxyFallback { get; private set; }
        public VideoPlayer Video { get; private set; }

        float savedSpeed;
        readonly System.Diagnostics.Stopwatch seekWatch = new System.Diagnostics.Stopwatch();

        // The decoder refuses to present the last few frames of a stream as
        // seek targets (observed on macOS/AVFoundation: requests into the
        // final ~3 frames settle on an earlier frame forever). The last
        // EndGuardFrames of media are therefore not seek/hold targets; the
        // effective window end clamps accordingly. Phase 10 renders real
        // media with padding past t1, making the guard invisible in product.
        public const int EndGuardFrames = 4;

        // Latest battle time the player will hold or seek to (valid while
        // entered; falls back to the metadata window before prepare).
        public double LastSeekableBattleTime
        {
            get
            {
                if (Active == null) return 0;
                double duration = (Video != null && Video.isPrepared && Video.length > 0)
                    ? System.Math.Min(Video.length, Active.t1 - Active.t0)
                    : Active.t1 - Active.t0;
                return Active.t0 + duration - EndGuardFrames / (double)Active.media.fps;
            }
        }

        public static string MediaPath(string relative)
            => Path.Combine(Application.streamingAssetsPath, relative);

        // Enterable only while the clock is inside [t0, t1) and media exists.
        public bool TryEnter(ViewpointDefinition vp)
        {
            if (InSoldierView || clock == null || vp == null) return false;
            string invalid = vp.Validate();
            if (invalid != null) { Warn($"viewpoint rejected: {invalid}"); return false; }
            if (!SoldierViewMath.WithinWindow(clock.CurrentTime, vp.t0, vp.t1))
            {
                Warn($"'{vp.id}' not enterable at t={clock.CurrentTime:0.00} " +
                     $"(window [{vp.t0}, {vp.t1}))");
                return false;
            }

            UsingProxyFallback = false;
            string path = vp.media.HasFull ? MediaPath(vp.media.full) : null;
            if (path == null || !File.Exists(path))
            {
                if (path != null)
                    Warn($"'{vp.id}' full media missing at {path}; falling back to proxy");
                path = MediaPath(vp.media.proxy);
                UsingProxyFallback = vp.media.HasFull;
                if (!File.Exists(path))
                {
                    Warn($"'{vp.id}' proxy media missing at {path}; " +
                         "run reconstruction/scripts/generate_dev_proxy.sh");
                    return false;
                }
            }

            Active = vp;
            savedSpeed = clock.Speed;
            clock.Speed = 1f; // pre-rendered media is 1 battle-second per second

            Video = gameObject.AddComponent<VideoPlayer>();
            Video.playOnAwake = false;
            Video.source = VideoSource.Url;
            Video.url = "file://" + path;
            Video.renderMode = VideoRenderMode.CameraNearPlane;
            Video.targetCamera = Camera.main;
            Video.aspectRatio = VideoAspectRatio.FitInside;
            Video.audioOutputMode = VideoAudioOutputMode.None;
            Video.skipOnDrop = true;
            Video.isLooping = false;
            // Settle detection: a paused decoder that has never played does
            // not reliably fire seekCompleted (observed on macOS/AVFoundation
            // in batchmode). SeekVideo() therefore plays through the seek and
            // we settle on whichever arrives first: the completed-seek event
            // or the first delivered frame.
            Video.sendFrameReadyEvents = true;
            Video.seekCompleted += OnSeekCompleted;
            Video.frameReady += OnFrameReady;
            Video.loopPointReached += OnLoopPointReached;
            Video.prepareCompleted += OnPrepared;
            Video.Prepare();
            return true;
        }

        public void Exit()
        {
            if (!InSoldierView) return;
            clock.Speed = savedSpeed;
            if (Video != null)
            {
                Video.seekCompleted -= OnSeekCompleted;
                Video.frameReady -= OnFrameReady;
                Video.loopPointReached -= OnLoopPointReached;
                Video.prepareCompleted -= OnPrepared;
                Destroy(Video);
                Video = null;
            }
            Active = null;
            SeekInProgress = false;
            // clock.CurrentTime is untouched: Atlas returns to this exact second.
        }

        public void SetPlaying(bool playing)
        {
            if (clock != null) clock.Playing = playing;
            if (!InSoldierView || Video == null || !Video.isPrepared || SeekInProgress) return;
            if (playing) Video.Play(); else Video.Pause();
        }

        // Seek both clock and video to a battle time (clamped into the
        // window). The decoder settles asynchronously; SeekInProgress is
        // true until it reports completion, and the settle latency is
        // recorded for the Phase 1 measurement.
        public void Seek(double battleTime)
        {
            if (!InSoldierView) return;
            double t = System.Math.Min(
                SoldierViewMath.ClampToWindow(
                    battleTime, Active.t0, Active.t1, Active.media.fps),
                LastSeekableBattleTime);
            clock.CurrentTime = (float)t;
            SeekVideo(SoldierViewMath.BattleToVideo(t, Active.t0));
        }

        void OnPrepared(VideoPlayer vp)
        {
            Seek(clock.CurrentTime);
        }

        double pendingSeekTime;

        void SeekVideo(double videoTime)
        {
            if (Video == null || !Video.isPrepared) return;
            // Seek to the CENTER of the target frame, never its boundary:
            // a request landing exactly on a frame PTS is ambiguous and
            // AVFoundation resolves it to the previous frame, which reads as
            // a full frame of drift. Center-of-frame requests land uniquely.
            double fps = Active != null ? Active.media.fps : 30.0;
            videoTime = (System.Math.Floor(videoTime * fps) + 0.5) / fps;
            SeekInProgress = true;
            pendingSeekTime = videoTime;
            seekWatch.Restart();
            Video.time = videoTime;
            // Play through the seek so the decoder actually delivers the
            // target frame; SettleSeek() re-pauses if the clock is paused.
            if (!Video.isPlaying) Video.Play();
        }

        // Decoder callbacks are treated as HINTS only: seekCompleted can fire
        // before the target frame is actually presented (observed on
        // macOS/AVFoundation), and frames delivered while playing through a
        // seek can start earlier than the target (keyframe roll-forward).
        // A seek is settled only when the PRESENTED frame is within half a
        // frame of the target — the frame containing it, not a neighbor.
        void OnSeekCompleted(VideoPlayer vp) => SettleIfArrived();

        void OnFrameReady(VideoPlayer vp, long frameIdx) => SettleIfArrived();

        // Seeking near the final frame can hit end-of-stream before any
        // other signal arrives.
        void OnLoopPointReached(VideoPlayer vp)
        {
            SettleIfArrived();
            Video.Pause();
        }

        void SettleIfArrived()
        {
            if (!SeekInProgress) return;
            double fps = Active != null ? Active.media.fps : 30.0;
            if (System.Math.Abs(Video.time - pendingSeekTime) * fps <= 0.5 + 1e-6)
                SettleSeek();
        }

        void SettleSeek()
        {
            if (!SeekInProgress) return;
            seekWatch.Stop();
            SeekInProgress = false;
            LastSeekLatencyMs = seekWatch.Elapsed.TotalMilliseconds;
            SeekLatenciesMs.Add(LastSeekLatencyMs);
            if (clock == null || !clock.Playing) Video.Pause();
        }

        void Update()
        {
            if (!InSoldierView || Video == null || !Video.isPrepared) return;

            // Window end: hold on the last presentable frame, paused. The
            // user exits explicitly; the clock never runs past the playable
            // end while inside.
            if (clock.CurrentTime >= LastSeekableBattleTime)
            {
                clock.CurrentTime = (float)LastSeekableBattleTime;
                if (clock.Playing) SetPlaying(false);
            }

            if (SeekInProgress)
            {
                // Event-less stalls happen (observed: seeking into the final
                // frame stops the decoder at end-of-stream with no callback).
                // After giving events a fair chance, settle from the poll
                // side when the decoder has stopped, or unconditionally after
                // a hard timeout so playback can never wedge.
                double elapsed = seekWatch.Elapsed.TotalSeconds;
                if (elapsed > 0.25 && !Video.isPlaying) SettleIfArrived();
                // Hard timeout: never wedge, even if the decoder cannot
                // reach the target (end-guard should make this unreachable).
                if (SeekInProgress && elapsed > 3.0) SettleSeek();
                return;
            }

            CurrentDriftFrames = SoldierViewMath.DriftFrames(
                Video.time, clock.CurrentTime, Active.t0, Active.media.fps);
            // While playing, small drift is tolerated (resync would stutter);
            // paused, the displayed frame must be the clock's frame — a
            // stale in-flight seek target (computed before a pause froze the
            // clock) is corrected here.
            float threshold = clock.Playing ? resyncThresholdFrames : 1f;
            if (Mathf.Abs((float)CurrentDriftFrames) > threshold)
            {
                SeekVideo(SoldierViewMath.BattleToVideo(clock.CurrentTime, Active.t0));
                return;
            }

            // Keep decoder play state honest with the clock.
            if (clock.Playing && !Video.isPlaying) Video.Play();
            else if (!clock.Playing && Video.isPlaying) Video.Pause();
        }

        void Warn(string message)
        {
            LastWarning = message;
            Debug.LogWarning($"SoldierView: {message}");
        }
    }
}
