"""Deterministic Soldier View captions (plan §12 Phase 12 accessibility).

Emits time-coded captions for the two authored VOICE layers of the
Soldier View mix — shouted orders (voices_unit shout bursts at segment
transitions) and wounded voices (voices_wounded) — by replaying the SAME
event streams, hash gates, geometry, and arrival-delay math
build_viewpoint_audio.py uses (imported, not copied). A caption therefore
exists exactly where an audible voice event exists in the shipped mix;
no caption is invented, and no worded dialogue is attributed (§9.2 —
the underlying audio is generic, unattributed shouting and sober groans,
so the captions are bracketed non-speech descriptions).

Times are BATTLE seconds (the product clock), including the same
speed-of-sound arrival delay the ear hears.

Usage (from reconstruction/):
  uv run python scripts/generate_captions.py \
      --events ../docs/benchmarks/captures/p9-gate/p9-audio-events.json \
      --t0 8160 --t1 8820.5 \
      [--out ../app/Assets/StreamingAssets/SoldierView/captions.json] \
      [--check]

--check regenerates and fails (exit 1) if the committed file is stale —
the generate_attribution.py discipline. The events export is the
gitignored render-side artifact (docs/reconstruction/render-runbook.md
§4 regenerates it); the committed captions.json is the small durable
product artifact, like credits.json.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_viewpoint_audio as bva  # noqa: E402

# Sober, bracketed non-speech captions (§9.2: no invented dialogue).
ORDERS_TEXT = "[shouted orders nearby]"
WOUNDED_TEXT = "[a wounded man cries out]"
WOUNDED_AGAIN_TEXT = "[the wounded man groans]"

ORDERS_DUR_S = 3.0
WOUNDED_DUR_S = 2.5


def build_captions(events: dict, t0: float | None, t1: float | None) -> dict:
    seed = events["seed"]
    w0 = float(t0 if t0 is not None else events["window"]["t0"])
    w1 = float(t1 if t1 is not None else events["window"]["t1"])
    track = bva.ObserverTrack(events["observer"])

    def in_window(at: float) -> bool:
        # build_viewpoint_audio.in_window: delayed arrivals may land in
        # the encode tail past t1
        return w0 <= at <= w1 + bva.TAIL_S

    captions: list[dict] = []

    # --- shouted orders: voices_unit shout bursts ------------------------
    for i, seg in enumerate(events["observerSegments"]):
        if seg["action"] not in bva.NOISY_ACTIONS:
            continue
        at = seg["t0"] + 0.8
        if not in_window(at):
            continue
        captions.append({
            "t": round(at, 3),
            "dur": ORDERS_DUR_S,
            "kind": "orders",
            "text": ORDERS_TEXT,
        })

    # --- wounded voices: voices_wounded (same sparse hash gate) ----------
    for i, e in enumerate(events["casualties"]):
        r, _pan = bva.geometry(track, e["t"], e["x"], e["z"])
        if r > bva.GROAN_RANGE_M:
            continue
        if bva.h01(seed, "groan", i) >= bva.GROAN_FRACTION:
            continue
        at = bva.arrival(e["t"] + 1.2 + 1.5 * bva.h01(seed, "groan-dt", i), r)
        if in_window(at):
            captions.append({
                "t": round(at, 3),
                "dur": WOUNDED_DUR_S,
                "kind": "wounded",
                "text": WOUNDED_TEXT,
            })
            if e["crawls"]:
                at2 = at + 6.0 + 4.0 * bva.h01(seed, "groan-again", i)
                if in_window(at2):
                    captions.append({
                        "t": round(at2, 3),
                        "dur": WOUNDED_DUR_S,
                        "kind": "wounded",
                        "text": WOUNDED_AGAIN_TEXT,
                    })

    captions.sort(key=lambda c: (c["t"], c["kind"], c["text"]))
    return {
        "viewpointId": events["viewpoint"],
        "seed": seed,
        "window": {"t0": w0, "t1": w1},
        "note": ("Generated by reconstruction/scripts/generate_captions.py "
                 "from the deterministic audio-event export; captions mirror "
                 "the voices_unit/voices_wounded events of the shipped mix. "
                 "Do not hand-edit."),
        "captions": captions,
    }


def render(doc: dict) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    repo = Path(__file__).resolve().parent.parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", required=True, type=Path)
    ap.add_argument("--t0", type=float, default=None)
    ap.add_argument("--t1", type=float, default=None)
    ap.add_argument(
        "--out", type=Path,
        default=repo / "app/Assets/StreamingAssets/SoldierView/captions.json")
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed captions.json is stale")
    args = ap.parse_args()

    events = json.loads(args.events.read_text())
    text = render(build_captions(events, args.t0, args.t1))

    if args.check:
        if not args.out.exists():
            print(f"STALE: {args.out} missing", file=sys.stderr)
            return 1
        if args.out.read_text() != text:
            print(f"STALE: {args.out} does not match the events export — "
                  "regenerate with scripts/generate_captions.py",
                  file=sys.stderr)
            return 1
        print(f"ok: {args.out} is current")
        return 0

    args.out.write_text(text)
    doc = json.loads(text)
    kinds = {}
    for c in doc["captions"]:
        kinds[c["kind"]] = kinds.get(c["kind"], 0) + 1
    print(f"wrote {args.out}: {len(doc['captions'])} captions {kinds}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
