#!/usr/bin/env python3
"""Generate the Atlas command overlay (unit id -> corps / division).

The cartography slice's altitude-driven label policy shows CORPS labels at
theater height and DIVISION labels at mid height. The battle file carries
no corps/division records; the audited OOB register does, as each entry's
parentChain (docs/reconstruction/audit/oob-register.json, castStatus = the
in-build unit id). This script joins the two and emits a small overlay
JSON the runtime loads from Resources — display names verbatim from the
register (never invented), deterministic output (sorted by unit id).

Children of decomposed brigades (units with `parent` in the battle file)
inherit their parent's chain. Divisions with generic ordinal names
("1st Division") are qualified with their corps for display uniqueness;
named divisions ("Pickett's Division") stand alone, exactly as recorded.

Usage: scripts/gen-command-overlay.py   (from the repo root; rewrites
       app/Assets/Resources/Battle/command-overlay.json)
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTER = os.path.join(REPO, "docs/reconstruction/audit/oob-register.json")
# Every reconstructed phase file contributes unit ids (ADR 0005: one file
# per phase; the runtime skips overlay entries the loaded battle lacks).
BATTLES = [
    os.path.join(REPO, "app/Assets/Battle/gettysburg-july3.json"),
    os.path.join(REPO, "app/Assets/Battle/gettysburg-july3-morning.json"),
    os.path.join(REPO, "app/Assets/Battle/gettysburg-july2-afternoon.json"),
    os.path.join(REPO, "app/Assets/Battle/gettysburg-july2-evening.json"),
    os.path.join(REPO, "app/Assets/Battle/gettysburg-july1-morning.json"),
    os.path.join(REPO, "app/Assets/Battle/gettysburg-july1-afternoon.json"),
]
OUT = os.path.join(REPO, "app/Assets/Resources/Battle/command-overlay.json")

# Units the register represents only INSIDE another entry (name-only
# regiment strings), yet which are parentless units in the build. Chains
# cited from the register entry that contains them.
MANUAL_CHAINS = {
    # 8th Ohio: detached from Carroll's brigade (1st Bde, 3rd Div, II
    # Corps) — the register carries it inside reg-us-ii-3-1's regiments.
    "us-8oh": ["Army of the Potomac", "II Corps", "3rd Division"],
    # Decomposition wave 1 (docs/reconstruction/audit/decomposition-wave-1.md):
    # three more parentless single-regiment promotions, same us-8oh pattern
    # — the register carries each inside its brigade entry's regiments list.
    "us-6wi": ["Army of the Potomac", "I Corps", "1st Division"],  # reg-us-i-1-1 (Meredith's)
    "us-147ny": ["Army of the Potomac", "I Corps", "1st Division"],  # reg-us-i-1-2 (Cutler's)
    "us-16me": ["Army of the Potomac", "I Corps", "2nd Division"],  # reg-us-i-2-1 (Paul's)
    # July 3 morning slice (docs/reconstruction/audit/july3-morning-slice.md,
    # ED-76): the 2nd Massachusetts / 27th Indiana Spangler's Meadow charge,
    # promoted parentless out of Colgrove's brigade — same pattern.
    "us-2ma": ["Army of the Potomac", "XII Corps", "1st Division"],  # reg-us-xii-1-3 (Colgrove's)
    "us-27in": ["Army of the Potomac", "XII Corps", "1st Division"],  # reg-us-xii-1-3 (Colgrove's)
}

GENERIC_DIVISION = re.compile(r"^\d+(st|nd|rd|th) (Division|Brigade)")


def main():
    register = json.load(open(REGISTER))

    chains = dict(MANUAL_CHAINS)
    for entry in register["entries"]:
        cast = entry.get("castStatus")
        if cast and cast != "not-yet-cast":
            chains[cast] = entry.get("parentChain") or []

    units = {}
    for path in BATTLES:
        for u in json.load(open(path))["units"]:
            units.setdefault(u["id"], u)
    out_units = []
    unmapped = []
    for uid in sorted(units):
        chain = chains.get(uid)
        if chain is None:
            parent = units[uid].get("parent")
            chain = chains.get(parent) if parent else None
        if not chain or len(chain) < 2:
            unmapped.append(uid)
            continue
        corps = chain[1]
        division = chain[2] if len(chain) >= 3 else ""
        if division and GENERIC_DIVISION.match(division) and corps not in division:
            division = f"{division}, {corps}"
        out_units.append({
            "id": uid,
            "corps": corps,
            "division": division,
        })

    doc = {
        "comment": "GENERATED by scripts/gen-command-overlay.py from the "
                   "audited OOB register (docs/reconstruction/audit/"
                   "oob-register.json parentChain) — do not hand-edit. "
                   "Feeds the altitude-driven label policy: corps labels "
                   "at theater height, division labels at mid height.",
        "units": out_units,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(doc, f, indent=1, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {OUT}: {len(out_units)} mapped, {len(unmapped)} unmapped")
    if unmapped:
        print("unmapped (no register chain — these units simply never join "
              "an aggregate label):", ", ".join(unmapped))
        return 1 if len(unmapped) > 5 else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
