using System;
using UnityEngine;

namespace BattleAtlas
{
    // Time-coded captions for the authored Soldier View voice layers
    // (plan §12 P12 accessibility: "subtitle/caption option for shouted
    // orders"). The data is StreamingAssets/SoldierView/captions.json,
    // generated by reconstruction/scripts/generate_captions.py from the
    // SAME deterministic event streams and hash gates the audio mix is
    // built from (build_viewpoint_audio.py) — a caption exists exactly
    // where an audible voice event exists; no caption is invented.
    //
    // Times are battle seconds (the clock the whole product runs on), so
    // display needs no media-time conversion.
    [Serializable]
    public class CaptionDto
    {
        public double t;      // battle time the caption appears
        public double dur;    // seconds visible
        public string kind;   // "orders" | "wounded"
        public string text;   // bracketed non-speech caption, sober wording
    }

    [Serializable]
    public class CaptionTrack
    {
        public string viewpointId;
        public CaptionDto[] captions;

        public static CaptionTrack FromJson(string json)
        {
            var track = JsonUtility.FromJson<CaptionTrack>(json);
            if (track?.captions == null)
                throw new ArgumentException("captions.json: no captions array");
            double prev = double.NegativeInfinity;
            foreach (CaptionDto c in track.captions)
            {
                if (c == null || string.IsNullOrEmpty(c.text))
                    throw new ArgumentException("captions.json: caption without text");
                if (c.dur <= 0)
                    throw new ArgumentException(
                        $"captions.json: non-positive duration at t={c.t}");
                if (c.t < prev)
                    throw new ArgumentException(
                        $"captions.json: captions not sorted at t={c.t}");
                prev = c.t;
            }
            return track;
        }

        // The caption text visible at battle time t: every caption whose
        // window covers t, newest first (a fresh cry reads above a fading
        // one), joined by newlines, capped at MaxLines so a dense casualty
        // window cannot wall the screen. Empty string = nothing visible.
        public const int MaxLines = 2;

        public string TextAt(double t)
        {
            if (captions == null || captions.Length == 0) return "";
            string result = "";
            int lines = 0;
            for (int i = captions.Length - 1; i >= 0 && lines < MaxLines; i--)
            {
                CaptionDto c = captions[i];
                if (c.t > t) continue;      // not started (sorted: keep scanning down)
                if (t >= c.t + c.dur) continue; // expired; earlier ones may still run
                result = lines == 0 ? c.text : result + "\n" + c.text;
                lines++;
            }
            return result;
        }
    }
}
