// Task 2 scale-fixture generator (plan: docs/superpowers/plans/2026-07-02-full-cast.md).
// Dogfoods the Task 1 generator lib at the full-cast target scale: a SYNTHETIC
// 210-unit battle (190 statics on a grid + 20 movers + 40 events) written to
// the Unity EditMode test fixtures so BattleLoaderScaleTests can retire the
// unit-count perf risk BEFORE any wave authors real units. Everything here is
// deliberately, loudly fake — "Test" names, synthetic citations — mirroring
// the placeholder-battle honesty convention. Deterministic: no randomness,
// so the committed fixture regenerates byte-identical. Run from tool/:
//   npx vite-node scripts/make-scale-fixture.ts
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { exportBattle } from "../src/io";
import { validateBattle } from "../src/validate";
import type { Battle, EngagementEvent, Unit } from "../src/model";
import { fireEvent, moverUnit, staticUnit, WindowEndT } from "./fullcast-lib";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(
  here, "../../app/Assets/Tests/Editor/Fixtures/scale-fixture-210.json");

const cite =
  "SYNTHETIC scale fixture — not historical; generated by tool/scripts/make-scale-fixture.ts";

const units: Unit[] = [];

// ---- 190 statics on a grid (the ~150-new-parentless-statics case, oversized) ----
// 19 columns x 10 rows inside the 8507 m square, both sides interleaved,
// strengths varied so heuristic frontages vary like a real cast.
for (let i = 0; i < 190; i++) {
  const col = i % 19;
  const row = Math.floor(i / 19);
  const side = i % 2 === 0 ? "union" : "confederate";
  units.push(staticUnit({
    id: `sf-static-${String(i + 1).padStart(3, "0")}`,
    name: `Test Static Brigade ${i + 1}`,
    side,
    strength: 300 + (i % 13) * 100, // 300..1500
    x: 1200 + col * 330,
    z: 1400 + row * 600,
    facing: side === "union" ? 262 : 82,
    formation: i % 7 === 0 ? "column" : "line",
    grade: i % 11 === 0 ? "C" : "B", // exercise both confidence mappings
    citation: i % 11 === 0 ? undefined : cite,
  }));
}

// ---- 20 movers with attested-shaped multi-keyframe tracks ---------------------
// First/last keyframes deliberately INSIDE the window (t=600..10500) so the
// Unity StateAt test exercises clamping on both ends of every mover.
for (let i = 0; i < 20; i++) {
  const x0 = 1500 + i * 300;
  const z0 = 2800 + (i % 4) * 150;
  const side = i % 2 === 0 ? "union" : "confederate";
  const strength = 400 + i * 40;
  units.push(moverUnit({
    id: `sf-mover-${String(i + 1).padStart(2, "0")}`,
    name: `Test Moving Battery ${i + 1}`,
    side,
    depth_m: 40,
    keyframes: [
      { t: 600, x: x0, z: z0, facing: 200, formation: "column", strength,
        confidence: "inferred", citation: cite },
      { t: 4200, x: x0 + 120, z: z0 + 260, facing: 231, formation: "column",
        strength: strength - 10, confidence: "inferred", citation: cite },
      { t: 7200, x: x0 + 60, z: z0 + 420, facing: 262, formation: "line",
        strength: strength - 20, confidence: "inferred", citation: cite },
      { t: 10500, x: x0 + 60, z: z0 + 420, facing: 262, formation: "line",
        strength: strength - 30, confidence: "inferred", citation: cite },
    ],
  }));
}

// ---- 40 events: the ~30-emitter cannonade peak + repulse musketry -------------
const events: EngagementEvent[] = [];
// 30 artillery windows all overlapping t=420..7200 (20 on statics, 10 on
// movers — moving emitters resolve positions from their tracks)
for (let i = 0; i < 30; i++) {
  const unitId = i < 20
    ? `sf-static-${String(i * 9 + 1).padStart(3, "0")}`
    : `sf-mover-${String(i - 19).padStart(2, "0")}`;
  events.push(fireEvent({
    id: `sf-ev-art-${String(i + 1).padStart(2, "0")}`,
    kind: "artillery_fire",
    t0: 420 + (i % 5) * 60,
    t1: 6600 + (i % 4) * 150,
    unitId,
    confidence: "inferred",
    citation: cite,
  }));
}
// 8 musketry windows in the repulse band
for (let i = 0; i < 8; i++) {
  events.push(fireEvent({
    id: `sf-ev-mus-${String(i + 1).padStart(2, "0")}`,
    kind: "musketry",
    t0: 8100 + i * 120,
    t1: 9600 + i * 120,
    unitId: `sf-static-${String(i * 17 + 3).padStart(3, "0")}`,
    confidence: "inferred",
    citation: cite,
  }));
}
// 2 fixed-segment emitters (the attested-detachment form stays exercised)
for (let i = 0; i < 2; i++) {
  events.push(fireEvent({
    id: `sf-ev-seg-${String(i + 1).padStart(2, "0")}`,
    kind: "artillery_fire",
    t0: 420,
    t1: 7200,
    segment: { x: 2000 + i * 3000, z: 7300, x2: 2600 + i * 3000, z2: 7250 },
    confidence: "inferred",
    citation: cite,
  }));
}

const battle: Battle = {
  name: "Scale fixture (synthetic, 210 units)",
  startTime: 46800,
  endTime: WindowEndT,
  units,
  events,
};

const result = validateBattle(battle);
if (!result.ok) {
  console.error(result.errors.join("\n"));
  throw new Error("scale fixture failed validation");
}
for (const w of result.warnings) console.log("warning: " + w);
writeFileSync(outPath, exportBattle(battle) + "\n");
console.log(`wrote ${outPath}: ${battle.units.length} units, ${events.length} events`);
